FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

# Added postgresql-client for DB searches and psmisc for process control
RUN apt-get update && \
    apt-get install -y calibre curl python3 djvulibre-bin psmisc postgresql-client && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY convert.sh /convert.sh
COPY bot.sh /bot.sh
RUN chmod +x /convert.sh /bot.sh

# Start both bot and converter
CMD bash -c "/bot.sh & /convert.sh; kill %1"
