name: vailib
services:
    vailib:
        cpu_shares: 90
        command: []
        container_name: vailib
        depends_on:
            sopds-db:
                condition: service_started
                required: true
        deploy:
            resources:
                limits:
                    memory: "16736321536"
        environment:
            DB_HOST: sopds-db
            DB_NAME: sopds
            DB_PASS: "${DB_PASSWORD:-changeme}"
            DB_PORT: "5432"
            DB_USER: sopds
            PGID: "0"
            PUID: "0"
            TIME_ZONE: Europe/Madrid
            SOPDS_TMBOT_ENABLE: "False"
            SOPDS_TELEBOT_AUTH: "True"
            SOPDS_TMBOT_TOKEN: "${BOT_TOKEN:-YOUR_TELEGRAM_BOT_TOKEN}"
            BOT_TOKEN: "${BOT_TOKEN:-YOUR_TELEGRAM_BOT_TOKEN}"
            CHAT_ID: "${CHAT_ID:-YOUR_TELEGRAM_CHAT_ID}"
        hostname: vailib
        image: vailib:latest
        labels:
            icon: ${SOPDS_ICON_URL:-https://example.com/icon.jpeg}
        networks:
            default: null
        ports:
            - mode: ingress
              target: 8001
              published: "8081"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/sopds/db
              target: /var/lib/sopds
              bind:
                create_host_path: true
            - type: bind
              source: /DATA/Downloads/books
              target: /library
              bind:
                create_host_path: true
    sopds-db:
        cpu_shares: 90
        command: []
        container_name: sopds-db
        deploy:
            resources:
                limits:
                    memory: "16736321536"
        environment:
            POSTGRES_DB: sopds
            POSTGRES_PASSWORD: "${DB_PASSWORD:-changeme}"
            POSTGRES_USER: sopds
        hostname: sopds-db
        image: postgres:13-alpine
        labels:
            icon: ${SOPDS_ICON_URL:-https://example.com/icon.jpeg}
        networks:
            default: null
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/sopds/postgres
              target: /var/lib/postgresql/data
              bind:
                create_host_path: true
networks:
    default:
        name: sopds_default
x-casaos:
    author: self
    category: self
    hostname: ${SOPDS_HOSTNAME:-example.com}
    icon: ${SOPDS_ICON_URL:-https://example.com/icon.jpeg}
    index: /
    is_uncontrolled: false
    port_map: ""
    scheme: http
    title:
        custom: SOPDS
